ENTITY_REGISTRY = [
    # ── E-COMMERCE ────────────────────────────────────────────────────────────
    {
        "canonical": "AMAZON",
        "aliases": ["AMAZON", "AMAZON PAY", "AMZN", "AMAZON SELLER"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "FLIPKART",
        "aliases": ["FLIPKART", "FLIPKARTPAYMEN", "AULT EXPRESS FLIPKART", "EKART", "FLIPKART INTERNET"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SWIGGY",
        "aliases": ["SWIGGY", "SWIGGY INSTAMART", "BUNDL TECHNOLOGIES"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ZOMATO",
        "aliases": ["ZOMATO", "ZOMATO LIMITED", "ZOMATO MEDIA"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MYNTRA",
        "aliases": ["MYNTRA", "MYNTRA DESIGNS"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "NYKAA",
        "aliases": ["NYKAA", "FSN ECOMMERCE", "NYKAA FASHION"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BIGBASKET",
        "aliases": ["BIGBASKET", "BIG BASKET", "SUPERMARKET GROCERY"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ZEPTO",
        "aliases": ["ZEPTO", "KIRANAKART", "KIRANA KART"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BLINKIT",
        "aliases": ["BLINKIT", "BLINK COMMERCE", "GROFERS"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MEESHO",
        "aliases": ["MEESHO", "FASHNEAR TECHNOLOGIES"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SNAPDEAL",
        "aliases": ["SNAPDEAL", "SNAP DEAL"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "AJIO",
        "aliases": ["AJIO", "RELIANCE RETAIL AJIO"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "JIOMART",
        "aliases": ["JIOMART", "JIO MART", "RELIANCE JIO MART"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "TATA CLIQ",
        "aliases": ["TATA CLIQ", "TATACLIQ", "TATA CLiQ"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SHOPSY",
        "aliases": ["SHOPSY"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "DUNZO",
        "aliases": ["DUNZO"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "LENSKART",
        "aliases": ["LENSKART"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "PEPPERFRY",
        "aliases": ["PEPPERFRY", "PEPPER FRY"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    # ── FUEL ─────────────────────────────────────────────────────────────────
    {
        "canonical": "SUPER FILLINGS",
        "aliases": ["SUPER FILLINGS"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BPCL",
        "aliases": ["BPCL", "BHARAT PETROLEUM", "BHARAT PETROL"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "HPCL",
        "aliases": ["HPCL", "HINDUSTAN PETROLEUM", "HP PETROL"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "INDIAN OIL",
        "aliases": ["INDIAN OIL", "IOCL", "INDIANOIL", "INDIAN OIL CORP"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SHELL",
        "aliases": ["SHELL PETROL", "SHELL PETROLEUM", "SHELL INDIA"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "NAYARA ENERGY",
        "aliases": ["NAYARA", "NAYARA ENERGY", "ESSAR OIL"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "RELIANCE PETRO",
        "aliases": ["RELIANCE PETRO", "RELIANCE PETROLEUM", "RELIANCE FUEL"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.86,
        "ambiguity": "MEDIUM",
    },
    # ── TRAVEL ───────────────────────────────────────────────────────────────
    {
        "canonical": "IRCTC",
        "aliases": ["IRCTC", "INDIAN RAILWAY CATERING"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.95,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MAKEMYTRIP",
        "aliases": ["MAKEMYTRIP", "MAKE MY TRIP", "MMT"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "YATRA",
        "aliases": ["YATRA", "YATRA ONLINE"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "OYO",
        "aliases": ["OYO", "OYO ROOMS", "ORAVEL STAYS"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "OLA",
        "aliases": ["OLA", "OLA CABS", "ANI TECHNOLOGIES"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "UBER",
        "aliases": ["UBER", "UBER INDIA"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "REDBUS",
        "aliases": ["REDBUS", "RED BUS", "IBIBO GROUP"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "EASEMYTRIP",
        "aliases": ["EASEMYTRIP", "EASE MY TRIP", "EASY TRIP"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "CLEARTRIP",
        "aliases": ["CLEARTRIP", "CLEAR TRIP"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "GOIBIBO",
        "aliases": ["GOIBIBO", "GO IBIBO"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "INDIGO",
        "aliases": ["INDIGO", "INTERGLOBE AVIATION", "6E"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.86,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "AIR INDIA",
        "aliases": ["AIR INDIA", "AIRINDIA"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SPICEJET",
        "aliases": ["SPICEJET", "SPICE JET"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "VISTARA",
        "aliases": ["VISTARA", "TATA SIA AIRLINES"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "RAPIDO",
        "aliases": ["RAPIDO", "ROPPEN TRANSPORTATION"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    # ── INSURANCE ────────────────────────────────────────────────────────────
    {
        "canonical": "LIC",
        "aliases": ["LIC", "LIFE INSURANCE CORPORATION", "LIC OF INDIA", "LIC INDIA"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.95,
        "ambiguity": "LOW",
    },
    {
        "canonical": "APY",
        "aliases": ["APY", "PRAN", "ATAL PENSION"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "HDFC LIFE",
        "aliases": ["HDFC LIFE", "HDFC STANDARD LIFE", "HDFC LIFE INS", "HDFCLIFE"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ICICI PRUDENTIAL LIFE",
        "aliases": ["ICICI PRU LIFE", "ICICI PRUDENTIAL LIFE", "ICICI PRU", "ICICIPRULIFE"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SBI LIFE",
        "aliases": ["SBI LIFE", "SBI LIFE INS", "SBILIFE"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MAX LIFE",
        "aliases": ["MAX LIFE", "MAX LIFE INS", "MAX BUPA", "NIVA BUPA"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BAJAJ ALLIANZ",
        "aliases": ["BAJAJ ALLIANZ", "BAJAJ ALLIANZ LIFE", "BAJAJ ALLIANZ GEN", "BAJAJALLIANZ"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "TATA AIA",
        "aliases": ["TATA AIA", "TATA AIA LIFE", "TATA AIG"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "STAR HEALTH",
        "aliases": ["STAR HEALTH", "STAR HEALTH INS", "STAR HEALTH AND ALLIED"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "NEW INDIA ASSURANCE",
        "aliases": ["NEW INDIA ASSURANCE", "NEW INDIA INS", "NEW INDIA ASSUR"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ORIENTAL INSURANCE",
        "aliases": ["ORIENTAL INSURANCE", "ORIENTAL INS"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "NATIONAL INSURANCE",
        "aliases": ["NATIONAL INSURANCE", "NATIONAL INS CO"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "UNITED INDIA INSURANCE",
        "aliases": ["UNITED INDIA", "UNITED INDIA INS", "UIIC"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ACKO",
        "aliases": ["ACKO", "ACKO GENERAL"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "DIGIT INSURANCE",
        "aliases": ["DIGIT", "DIGIT INSURANCE", "GO DIGIT"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "CARE HEALTH",
        "aliases": ["CARE HEALTH", "CARE INSURANCE", "RELIGARE HEALTH"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "KOTAK LIFE",
        "aliases": ["KOTAK LIFE", "KOTAK MAHINDRA LIFE", "KOTAK LIFE INS"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    # ── RECHARGE / TELECOM ───────────────────────────────────────────────────
    {
        "canonical": "AIRTEL",
        "aliases": ["AIRTEL", "BHARTI AIRTEL"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "JIO",
        "aliases": ["JIO", "JIO POSTPAID", "RELIANCE JIO", "RJIL"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "VI",
        "aliases": ["VI", "VODAFONE IDEA", "VODAFONE", "IDEA CELLULAR"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "BSNL",
        "aliases": ["BSNL", "BHARAT SANCHAR NIGAM"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "TATA TELESERVICES",
        "aliases": ["TATA TELESERVICES", "TATA TELE", "TATASKY", "TATA SKY"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "DISH TV",
        "aliases": ["DISH TV", "DISHTV", "D2H", "VIDEOCON D2H"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SUN DIRECT",
        "aliases": ["SUN DIRECT", "SUNDIRECT"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    # ── UTILITY BILLERS ──────────────────────────────────────────────────────
    {
        "canonical": "BESCOM",
        "aliases": ["BESCOM", "BANGALORE ELECTRICITY"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MSEDCL",
        "aliases": ["MSEDCL", "MSEB", "MAHARASHTRA STATE ELECTRICITY", "MAHADISCOM"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "TNEB",
        "aliases": ["TNEB", "TANGEDCO", "TAMILNADU ELECTRICITY"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "KSEB",
        "aliases": ["KSEB", "KERALA STATE ELECTRICITY"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "WBSEDCL",
        "aliases": ["WBSEDCL", "WEST BENGAL ELECTRICITY"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "UPPCL",
        "aliases": ["UPPCL", "UTTAR PRADESH POWER CORP", "PURVANCHAL VIDYUT"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BSES",
        "aliases": ["BSES", "BSES RAJDHANI", "BSES YAMUNA"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "TATA POWER",
        "aliases": ["TATA POWER", "TATAPOWER", "TATA POWER DDL"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.90,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "ADANI ELECTRICITY",
        "aliases": ["ADANI ELECTRICITY", "ADANI ELEC", "ADANI POWER"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.90,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "CESC",
        "aliases": ["CESC", "CESC LIMITED"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MAHANAGAR GAS",
        "aliases": ["MAHANAGAR GAS", "MGL", "MAHANAGAR GAS LTD"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "IGL",
        "aliases": ["IGL", "INDRAPRASTHA GAS", "INDRAPRASHTHA GAS"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "GUJARAT GAS",
        "aliases": ["GUJARAT GAS", "GAIL GAS"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    # ── LOAN / LENDERS ───────────────────────────────────────────────────────
    {
        "canonical": "BAJAJ FINANCE",
        "aliases": ["BAJAJ FINANCE", "BAJAJ FINANCELTD", "BAJAJ FINSERV", "BAJAJFINANCE"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "HDB FINANCIAL SERVICES",
        "aliases": ["HDB FINANCIAL SERVICES", "HDBFINANCIALSERVIC", "HDB FINANCIAL", "HDBFIN", "HDBFS"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "GROWTH SOURCE FINANCE",
        "aliases": ["GROWTH SOURCE FINANCE", "GROWTHSOURCEFINANC", "GROWTH SOURCE FINANC"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "HDFC HOME LOANS",
        "aliases": ["HDFC HOME LOAN", "HDFC LTD", "HDFC CREDILA"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "ICICI HOME FINANCE",
        "aliases": ["ICICI HOME FINANCE", "ICICI HFC", "ICICI BANK HOME LOAN"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "TATA CAPITAL",
        "aliases": ["TATA CAPITAL", "TATA CAP", "TATA CAPITAL FINANC"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "L&T FINANCE",
        "aliases": ["L&T FINANCE", "L AND T FINANCE", "LT FINANCE", "LNTFIN"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MUTHOOT FINANCE",
        "aliases": ["MUTHOOT FINANCE", "MUTHOOT FIN", "MUTHOOTFIN"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MANAPPURAM FINANCE",
        "aliases": ["MANAPPURAM", "MANAPPURAM FINANCE", "MANAPPURAM FIN"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "IIFL FINANCE",
        "aliases": ["IIFL FINANCE", "IIFL", "INDIA INFOLINE FINANCE"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "POONAWALLA FINCORP",
        "aliases": ["POONAWALLA FINCORP", "POONAWALLA FIN", "MAGMA FINCORP"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "FULLERTON INDIA",
        "aliases": ["FULLERTON", "FULLERTON INDIA", "SMFG INDIA"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "HERO FINCORP",
        "aliases": ["HERO FINCORP", "HERO FIN CORP", "HERO FINANCECORP"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SHRIRAM FINANCE",
        "aliases": ["SHRIRAM FINANCE", "SHRIRAM TRANSPORT", "STFC", "SCUF"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "CAPITAL FLOAT",
        "aliases": ["CAPITAL FLOAT", "CAPITALFLOAT", "AXIO"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "HOME CREDIT",
        "aliases": ["HOME CREDIT", "HOMECREDIT"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "NAVI FINSERV",
        "aliases": ["NAVI FINSERV", "NAVI", "CHAITANYA INDIA"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "MONEYVIEW",
        "aliases": ["MONEYVIEW", "MONEY VIEW", "WHIZDM"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "KREDITBEE",
        "aliases": ["KREDITBEE", "KREDIT BEE", "FINNOV"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "STASHFIN",
        "aliases": ["STASHFIN", "STASH FIN"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "INCRED",
        "aliases": ["INCRED", "INCRED FINANCE"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "PAYSENSE",
        "aliases": ["PAYSENSE", "PAY SENSE", "GAURAV SHUB"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    # ── INVESTMENTS ──────────────────────────────────────────────────────────
    {
        "canonical": "ZERODHA",
        "aliases": ["ZERODHA", "ZERODHA BROKING", "ZERODHA SECURITIES"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "GROWW",
        "aliases": ["GROWW", "NEXTBILLION TECHNOLOGY"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "UPSTOX",
        "aliases": ["UPSTOX", "RKSV SECURITIES"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "KUVERA",
        "aliases": ["KUVERA", "AREVUK ADVISORY"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "PAYTM MONEY",
        "aliases": ["PAYTM MONEY", "PAYTMMONEY"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "5PAISA",
        "aliases": ["5PAISA", "5 PAISA", "FIVE PAISA"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ANGEL ONE",
        "aliases": ["ANGEL ONE", "ANGEL BROKING", "ANGEL SECURITIES"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "HDFC MF",
        "aliases": ["HDFC MUTUAL FUND", "HDFC AMC", "HDFCMF"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "SBI MF",
        "aliases": ["SBI MUTUAL FUND", "SBI MF", "SBI FUNDS MANAGEMENT"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "ICICI PRU AMC",
        "aliases": ["ICICI PRUDENTIAL AMC", "ICICI PRU AMC", "ICICICICIPRUMF"],
        "category": "INVESTMENTS",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    # ── CREDIT CARD PAYMENT ───────────────────────────────────────────────────
    {
        "canonical": "CRED",
        "aliases": ["CRED", "PAID VIA CRED", "PAIDVIACRED"],
        "category": "CREDIT CARD PAYMENT",
        "role": "card_payment_app",
        "confidence": 0.84,
        "ambiguity": "MEDIUM",
    },
    # ── PAYMENT GATEWAYS / CHANNELS ──────────────────────────────────────────
    {
        "canonical": "PHONEPE",
        "aliases": ["PHONEPE", "PHONE PE"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_channel",
        "confidence": 0.58,
        "ambiguity": "HIGH",
    },
    {
        "canonical": "PAYTM",
        "aliases": ["PAYTM", "ONE 97", "ONE97", "ONE 97 COMMUNICATIONS"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.72,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "MOBIKWIK",
        "aliases": ["MOBIKWIK"],
        "category": "PAYMENT GATEWAY",
        "role": "wallet",
        "confidence": 0.70,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "RAZORPAY",
        "aliases": ["RAZORPAY"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "PAYU",
        "aliases": ["PAYU", "PAY U"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "BILLDESK",
        "aliases": ["BILLDESK", "BILL DESK"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.78,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "CASHFREE",
        "aliases": ["CASHFREE", "CASHFREE PAYMENTS"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "CCAVENUE",
        "aliases": ["CCAVENUE", "CC AVENUE"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "LOW",
    },
    {
        "canonical": "INSTAMOJO",
        "aliases": ["INSTAMOJO"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "LOW",
    },
]
